### ISSUE TITLE
APPLICATION CRASH

### ISSUE THREAD

**Issue by jtrent238** [KristinnVikarJ/DiamondClicker#1]
```
`Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: Diamond Clicker V0.2.exe
  Application Version:  1.0.0.0
  Application Timestamp:    550c7a99
  Fault Module Name:    KERNELBASE.dll
  Fault Module Version: 6.1.7601.23392
  Fault Module Timestamp:   56eb2fb9
  Exception Code:   e0434352
  Exception Offset: 0000845d
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
`
```

![](http://puu.sh/qpRCl/99bd4fbba6.png)

**Comment by KristinnVikarJ** [comment]
What is your system drive on?, C: D:

**Comment by jtrent238** [comment]
C

**Comment by KristinnVikarJ** [comment]
Can you go to documents and send me the diamondclicker.dat if you can find it

**Comment by KristinnVikarJ** [comment]
Hmmm, it might be because i have never tested it in a windows 7 enviroment

**Comment by jtrent238** [comment]
Well I did have an older version and might have broke it (max it out).

**Comment by jtrent238** [comment]
```
-2032008886
412
244
250
299
0
0
0
0
```

**Comment by KristinnVikarJ** [comment]
Oh wow, how did you get so far?, and also you are really outtdated i use binary to store the data now, to fix the crash make the number a + number

**Comment by KristinnVikarJ** [comment]
does it crash at startup?, because it should never crash when reading the save as i have a try catch there :P

**Comment by jtrent238** [comment]
Startup, and I let it run overnight lol.

**Comment by KristinnVikarJ** [comment]
i just checked, the program never attempts to read the save until you click load save :O

**Comment by jtrent238** [comment]
Yea I remember having to Click load save, but in the new version is it still like that?

**Comment by KristinnVikarJ** [comment]
in the newer version if the load fails it just lets you know and stops trying to load it

**Comment by KristinnVikarJ** [comment]
and if you want to go to the newer version i can port your save for you

**Comment by jtrent238** [comment]
how do you port the save, and I am going to try and debug.

**Comment by KristinnVikarJ** [comment]
just put it in a binary translator, one line at a time, as now i save it in binary so its harder to read for people to cheat

**Comment by jtrent238** [comment]
is the source code the latest version ?

**Comment by KristinnVikarJ** [comment]
yes

**Comment by jtrent238** [comment]
Can you port my save?

**Comment by KristinnVikarJ** [comment]
sure, ill also fix it xD

**Comment by jtrent238** [comment]
What version Of Visual Studio did you make this in?

**Comment by KristinnVikarJ** [comment]
01111001000111011111111010110110
00000000000000000000000110011100
00000000000000000000000011110100
00000000000000000000000011111010
00000000000000000000000100101011
0
0
0
0
0
0
0

**Comment by KristinnVikarJ** [comment]
that is the save file
and i made it in visual studio 2012 and visual studio 2013

**Comment by jtrent238** [comment]
This just came up when I said Check for problem

```
Files that help describe the problem:
  C:\Users\trent\AppData\Local\Temp\WER5BB0.tmp.WERInternalMetadata.xml
  C:\Users\trent\AppData\Local\Temp\WER95D4.tmp.appcompat.txt
  C:\Users\trent\AppData\Local\Temp\WERF5EE.tmp.WERDataCollectionFailure.txt

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by KristinnVikarJ** [comment]
go to   C:\Users\trent\AppData\Local\Temp\WER95D4.tmp.appcompat.txt
and post the contents of it here

**Comment by jtrent238** [comment]
the file was not found

**Comment by KristinnVikarJ** [comment]
did you close the program and then check for the file?, if so then try doing the check for problem again and then go to the new middle link and post it here

**Comment by jtrent238** [comment]
it just closes when i click it now.

**Comment by KristinnVikarJ** [comment]
hmmm, im not sure, is this in the newest version of the program?

**Comment by jtrent238** [comment]
the one from pmc
[THIS LINK](https://dl.dropboxusercontent.com/content_link/njA2ycpotHnG0uxk9PDQSqspJCUD6sQSYriE0W8oZdIQohGQOcUgcnB6iejg8YyF/file?dl=1)

**Comment by KristinnVikarJ** [comment]
invalid link?

**Comment by KristinnVikarJ** [comment]
[This is the newer link](https://www.dropbox.com/s/h3ndj2i4uqjv3jd/Diamond%20Clicker%20V0.2.exe?dl=0)

**Comment by jtrent238** [comment]
Back

```
Files that help describe the problem:
  C:\Users\trent\AppData\Local\Temp\WERE808.tmp.WERInternalMetadata.xml
  C:\Users\trent\AppData\Local\Temp\WERF3AC.tmp.appcompat.txt
  C:\Users\trent\AppData\Local\Temp\WER3619.tmp.WERDataCollectionFailure.txt

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

```

**Comment by jtrent238** [comment]
[C:\Users\trent\AppData\Local\Temp\WERE808.tmp.WERInternalMetadata.xml](https://gist.github.com/jtrent238/bf52bffc93c3e88d54974af6f3027ae2/raw/48d43891b9fffc0637d4a0fbf3b35c2100582451/gistfile3.txt)
  [C:\Users\trent\AppData\Local\Temp\WERF3AC.tmp.appcompat.txt](https://gist.github.com/jtrent238/bf52bffc93c3e88d54974af6f3027ae2/raw/48d43891b9fffc0637d4a0fbf3b35c2100582451/gistfile1.txt)
 [ C:\Users\trent\AppData\Local\Temp\WER3619.tmp.WERDataCollectionFailure.txt](https://gist.github.com/jtrent238/bf52bffc93c3e88d54974af6f3027ae2/raw/48d43891b9fffc0637d4a0fbf3b35c2100582451/gistfile2.txt)

**Comment by jtrent238** [comment]
not sure if this is what your looking for:

```
<MATCHING_FILE NAME="Diamond Clicker V0.2 (1).exe" SIZE="25600" CHECKSUM="0x60E0FEB7" BIN_FILE_VERSION="1.0.0.0" BIN_PRODUCT_VERSION="1.0.0.0" PRODUCT_VERSION="1.0.0.0" FILE_DESCRIPTION="Clicker Game" PRODUCT_NAME="Clicker Game" FILE_VERSION="1.0.0.0" ORIGINAL_FILENAME="Diamond Clicker.exe" INTERNAL_NAME="Diamond Clicker.exe" LEGAL_COPYRIGHT="Copyright ©  2015" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="1.0.0.0" UPTO_BIN_PRODUCT_VERSION="1.0.0.0" LINK_DATE="03/20/2015 19:52:57" UPTO_LINK_DATE="03/20/2015 19:52:57" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="Diamond Clicker V0.2 (2).exe" SIZE="25600" CHECKSUM="0x60E0FEB7" BIN_FILE_VERSION="1.0.0.0" BIN_PRODUCT_VERSION="1.0.0.0" PRODUCT_VERSION="1.0.0.0" FILE_DESCRIPTION="Clicker Game" PRODUCT_NAME="Clicker Game" FILE_VERSION="1.0.0.0" ORIGINAL_FILENAME="Diamond Clicker.exe" INTERNAL_NAME="Diamond Clicker.exe" LEGAL_COPYRIGHT="Copyright ©  2015" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="1.0.0.0" UPTO_BIN_PRODUCT_VERSION="1.0.0.0" LINK_DATE="03/20/2015 19:52:57" UPTO_LINK_DATE="03/20/2015 19:52:57" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="Diamond Clicker V0.2.exe" SIZE="25600" CHECKSUM="0x60E0FEB7" BIN_FILE_VERSION="1.0.0.0" BIN_PRODUCT_VERSION="1.0.0.0" PRODUCT_VERSION="1.0.0.0" FILE_DESCRIPTION="Clicker Game" PRODUCT_NAME="Clicker Game" FILE_VERSION="1.0.0.0" ORIGINAL_FILENAME="Diamond Clicker.exe" INTERNAL_NAME="Diamond Clicker.exe" LEGAL_COPYRIGHT="Copyright ©  2015" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="1.0.0.0" UPTO_BIN_PRODUCT_VERSION="1.0.0.0" LINK_DATE="03/20/2015 19:52:57" UPTO_LINK_DATE="03/20/2015 19:52:57" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" />
    
```

**Comment by jtrent238** [comment]
Also This:

![](http://puu.sh/quzKG/6e8761edb5.png)

**Comment by KristinnVikarJ** [comment]
hrmm, im creating a crash handler that tries to write the crash into a log file wait a minute

**Comment by jtrent238** [comment]
im going to try to launch from visual studio

**Comment by KristinnVikarJ** [comment]
[Diamond Clicker V0.2.exe.zip](https://github.com/KristinnVikarJ/DiamondClicker/files/408002/Diamond.Clicker.V0.2.exe.zip)
try this, it should tell you the crash

**Comment by jtrent238** [comment]
Not sure if this is any different.

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Diamond Clicker V0.2.exe
  Application Version:	1.0.0.0
  Application Timestamp:	550c7a99
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.23392
  Fault Module Timestamp:	56eb2fb9
  Exception Code:	e0434352
  Exception Offset:	0000845d
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

```

**Comment by jtrent238** [comment]
![](http://puu.sh/quA6V/4538b2f702.png)

**Comment by KristinnVikarJ** [comment]
is this the file i sent you?

**Comment by jtrent238** [comment]
Oh and every time i try to open it this comes up also:

![](http://puu.sh/quA2e/55103a2472.png)

**Comment by jtrent238** [comment]
yes'

**Comment by KristinnVikarJ** [comment]
that is normal, it is because my program is new and needs to be scanned if it has viruses (which it does not have)

**Comment by jtrent238** [comment]
but do you think it is stopping it from starting?

**Comment by KristinnVikarJ** [comment]
did you try putting my code into visual studio and running it there, it should give you better logs
and no it should not stop it from starting

**Comment by jtrent238** [comment]
im trying to find visual studio

**Comment by jtrent238** [comment]
2012 is different than 2015 in where it istalls do you think it would work in 2015?

**Comment by KristinnVikarJ** [comment]
probably

**Comment by KristinnVikarJ** [comment]
oops, i sent an old file
that is why it did not tell you why it crashed

**Comment by KristinnVikarJ** [comment]
[Diamond Clicker.zip](https://github.com/KristinnVikarJ/DiamondClicker/files/408016/Diamond.Clicker.zip)

**Comment by jtrent238** [comment]
oh

**Comment by jtrent238** [comment]
loaded

**Comment by KristinnVikarJ** [comment]
it will create a text file on your desktop

**Comment by KristinnVikarJ** [comment]
if it crashes

**Comment by jtrent238** [comment]
![](http://puu.sh/quAHV/898329944a.png)

**Comment by KristinnVikarJ** [comment]
nice!

**Comment by KristinnVikarJ** [comment]
try loading the saved game

**Comment by jtrent238** [comment]
About The Text File!.. Prob wont find it...

![](http://puu.sh/quAK4/2a5c5d3dc3.jpg)

**Comment by jtrent238** [comment]
save game not working

**Comment by KristinnVikarJ** [comment]
?, how isnt it working

**Comment by jtrent238** [comment]
```
0
0
0
0
0
0
0
0
0

```

**Comment by jtrent238** [comment]
it reset

**Comment by KristinnVikarJ** [comment]
it probably just tried to fix itself because i accidently sent the wrong version

**Comment by KristinnVikarJ** [comment]
well you already finished the other save

**Comment by jtrent238** [comment]
Now I have done broke it lol

![](http://puu.sh/quB3Z/d414edf513.png)

**Comment by KristinnVikarJ** [comment]
Ill just change the diamonds to decimal

**Comment by KristinnVikarJ** [comment]
well your save will not be safe, in the never version i redid the whole save file thing, it is impossible to change without a program doing it for you
